# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    weight: 10
    url: '#about'
  - name: Projects
    url: '#projects'
    weight: 30
  - name: People
    url: '#people'
    weight: 35
  - name: Publications
    url: '#publications'
    weight: 50
  - name: Collaborators
    url: '#collaborators'
    weight: 55
  - name: Contact
    url: '#contact'
    weight: 60
